version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /data/tickets && minio server /data'
    environment:
      - MINIO_ROOT_USER=rubiezzy
      - MINIO_ROOT_PASSWORD=a3JsY4VnfT8s

  database:
    image: postgres
    restart: always
    build:
      context: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2587
      POSTGRES_DB: cinema
    volumes:
      - ./database/cinemadb.sql:/docker-entrypoint-initdb.d/cinemadb.sql
      - ./database/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql

  cinema-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
    ports:
      - "8080:8080"
    depends_on:
      - database
      - minio
    environment:
      - DATABASE_URL=${DATABASE_URL:?}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:?}

