version: '3'
services:
  database:
    image: postgres
    restart: always
    build:
      context: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2587
      POSTGRES_DB: cinema
    volumes:
      - ./database/cinemadb.sql:/docker-entrypoint-initdb.d/cinemadb.sql
      - ./database/mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql

  cinema-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:2587@database:5432/cinema?sslmode=disable"